# This is an example json schema for the 
# service. It is JSON schema but in yaml format.
#
# type: object
#   required:
#     - tag
#   properties:
#     tag:
#       type: string
#       pattern: v(.)*
#     pushtag:
#       type: boolean